services:
  - type: web
    name: django-posts-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn postsapp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: postsapp.settings 